# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Push artifacts to Harbor artifactory
description: Push artifacts to Harbor artifactory

inputs:
  HARBOR_UNAME:
    description: 'user account for artifactory'
    required: true
  HARBOR_TOKEN:
     description: 'api-key for artifactory'
     required: true
  HARBOR_URL:
    description: 'artifactory url'
    required: true
  input-paths:
    description: 'input-paths'
    required: true

runs:
  using: "composite"
  steps:
    - name: Preparing artifactory for upload
      uses: oras-project/setup-oras@v1
    - run: oras version
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: upload.sh
      env:
        HARBOR_UNAME: ${{ inputs.HARBOR_UNAME }}
        HARBOR_TOKEN: ${{ inputs.HARBOR_TOKEN }}
        HARBOR_URL: ${{ inputs.HARBOR_URL }}
        INPUT_PATHS: ${{ inputs.input-paths }}
      shell: bash
