# SPDX-FileCopyrightText: 2023-2024 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: build

on:
  push:
    branches:
      - "gh_actions_updates"

permissions:
  contents: read

jobs:
  build_target:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: Build FMO-OS
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Get nixpkgs revision
        id: nixpkgs_rev
        run: |
          echo "NIXPKGS_REV=https://github.com/nixos/nixpkgs/archive/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock).tar.gz" >> $GITHUB_OUTPUT
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          #nix_path: nixpkgs=${{ steps.nixpkgs_rev.outputs.NIXPKGS_REV }}
          #nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= prod-cache.vedenemo.dev~1:JcytRNMJJdYJVQCYwLNsrfVhct5dhCK2D3fa6O1WHOI= cache.ssrcdevops.tii.ae:oOrzj9iCppf+me5/3sN/BxEkp5SaFkHfKTPPZ97xXQk=
            trusted-substituters = https://cache.nixos.org https://prod-cache.vedenemo.dev https://cache.ssrcdevops.tii.ae
            substituters = https://cache.nixos.org https://prod-cache.vedenemo.dev https://cache.ssrcdevops.tii.ae
      #- name: Show nix-info & nixpkgs version
      #  run: |
      #    echo "Show nix-info"
      #    nix-shell -p nix-info --run "nix-info -m"
      #    echo "Show nixpkgs version"
      #    nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: fmo-os
          authToken: ${{ secrets.CACHIX_TOKEN }}
        #run: |
        #  nix-env -iA cachix -f https://cachix.org/api/v1/install
        #  cachix authtoken ${{ secrets.CACHIX_TOKEN }}
        #  cachix use fmo-os
      - name: Build
        run: |
          SSH_DIR=$HOME/.ssh

          mkdir -p $SSH_DIR
          echo '${{ secrets.RA_TOKEN }}' > $SSH_DIR/id_rsa
          chmod 0600 $SSH_DIR/id_rsa
          ssh-keyscan -t ed25519 -H github.com > $SSH_DIR/known_hosts
          chmod 600 $SSH_DIR/known_hosts

          nix flake show
          cachix watch-exec fmo-os -- nix build --print-build-logs .#packages.x86_64-linux.fmo-os-installer-debug
          nix-collect-garbage
