# SPDX-FileCopyrightText: 2023-2024 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: build

on:
  push:
    branches:
      - 'gh_actions_updates'

permissions:
  contents: read

jobs:
  build_target:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: Build FMO-OS
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - name: Prepare build
        run: |
          sh -c "umask 377; echo '${{ secrets.BUILDER_SSH_KEY }}' >builder_key"
          sudo sh -c "echo '${{ vars.BUILDER_SSH_KNOWN_HOST }}' >>/etc/ssh/ssh_known_hosts"
      - name: Build
        id: build
        run: |
          BUILDER='${{ vars.BUILDER_X86 }}'
          NIX_FAST_BUILD_GITREF="1775c732"
          nix run github:Mic92/nix-fast-build/"$NIX_FAST_BUILD_GITREF"#nix-fast-build -- \
            --flake .#fmo-os-installer-debug \
            --remote "$BUILDER" \
            --remote-ssh-option IdentityFile builder_key \
            --option accept-flake-config true \
            --no-download --skip-cached --no-nom
