# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v24
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change || echo "nix fmt fails"
      - name: Check reuse lint
        run: nix develop --command reuse lint || echo "lint fails"
      - name: Check nix flake show runs successfully
        run: nix flake show
